"""add camera fields to detections

Revision ID: e68103904188
Revises: 80f75e8b6493
Create Date: 2026-04-23 13:18:33.929953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e68103904188'
down_revision = '80f75e8b6493'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('camera_id', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_column('camera_id')

    # ### end Alembic commands ###
